'use strict';
const assert=require('assert'),vm=require('vm'),fs=require('fs');
const Equipment=require('./MacarEquipment');
const axe={id:'iron_axe',n:'Iron Axe',k:'weapon'},bow={id:'light_crossbow',n:'Light Crossbow'},hammer={id:'macar_hammer',n:'War Hammer',k:'weapon'};
assert.equal(Equipment.kind(axe),'axe');
assert.equal(Equipment.kind({id:'shadow_cleaver',n:'Shadow Cleaver'}),'axe');
assert.equal(Equipment.kind({n:'Battleaxe',k:'weapon'}),'axe');
assert.equal(Equipment.kind({n:'Pickaxe',k:'weapon'}),null);
assert.equal(Equipment.kind({n:'Crossbow bolts',k:'ammo'}),null);
assert.equal(Equipment.kind({n:'Bow Shield'}),null);
const eq={primary:axe,weapon:axe,secondary:bow};
assert.equal(Equipment.heldKind(eq),'xbow','old saves retain equipped crossbow display');
Equipment.select(eq,axe);assert.equal(Equipment.heldKind(eq),'axe','selecting axe overrides retained bow');
Equipment.select(eq,bow);assert.equal(Equipment.heldKind(eq),'xbow','selecting bow overrides retained axe');
Equipment.select(eq,axe);Equipment.select(eq,{n:'Shield'});assert.equal(Equipment.heldKind(eq),'axe','armor does not switch the held weapon');
const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../saves/GameSave'),'utf8'),context);
const snapshot=context.GameSave.snapshot({ch:1,equipped:eq,packs:{macar:{magic:[axe,bow]}}});
const restored={};context.GameSave.applyCampaign(restored,snapshot);
assert.equal(Equipment.heldKind(restored.equipped),'axe','reload keeps selection when both weapons remain equipped');
assert.equal(restored.equipped.primary,restored.packs.macar.magic[0],'selection lives on canonical pack row');
Equipment.select(restored.equipped,restored.equipped.secondary);assert.equal(Equipment.heldKind(restored.equipped),'xbow');
delete restored.equipped.secondary;assert.equal(Equipment.heldKind(restored.equipped),'axe','doffing bow restores primary axe');
eq.primary=eq.weapon=hammer;Equipment.select(eq,hammer);assert.equal(Equipment.heldKind(eq),'maul','selecting hammer overrides retained bow');
console.log('Macar held-weapon selection and save reload passed');
