'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const {readRgba}=require('../qa/pngRgba');const root=path.join(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const fn=n=>html.match(new RegExp('function '+n+'\\([\\s\\S]*?\\n\\}'))[0];
const c={wallFaceH:()=>100,isTeethFaceWall:()=>false,isRubyNorthWall:()=>false,isTeethNorthWall:()=>false,hallWallH:()=>80};vm.createContext(c);vm.runInContext('const WALL_TEETH_FACE_SCALE=2.25;\n'+['isTeethAltarWestWall','teethFaceWallH','wallHeightOverride','applyTeethFaceWallHeight','cellWallH'].map(fn).join('\n'),c);
const L={n:1};for(let y=2;y<14;y++){assert(c.isTeethAltarWestWall(L,100,y));assert.equal(c.cellWallH(L,100,y),225);}assert(!c.isTeethAltarWestWall({n:2},100,4));assert(!c.isTeethAltarWestWall(L,100,14));assert(!c.isTeethAltarWestWall(L,99,4));
c.applyTeethFaceWallHeight(L);assert.equal(L.wallH['100,4'],L.wallH['107,1']);assert.equal(c.cellWallH(L,100,4),225);
assert(html.includes('const altarWest=isTeethAltarWestWall(L,x,y)?faceL:null;'));assert(html.includes("altarWest||(sf==='e'?secE:faceR)"));
const file=(html.match(/SPRITE_FILES\.altar_teeth='([^']+)'/)||[])[1];assert(file.endsWith('open_left_v12.png'));
const image=readRgba(path.join(root,file));const alpha=(x,y)=>image.data[(Math.floor(y*image.h)*image.w+Math.floor(x*image.w))*4+3];
assert.equal(alpha(.15,.22),0,'old baked left wall is transparent');assert.equal(alpha(.30,.16),0,'left coping is removed');assert(alpha(.80,.25)>240,'right wall retained');assert(alpha(.43,.4)>240,'altar retained');assert(alpha(.4,.8)>240,'platform retained');
assert(Math.abs(image.w/image.h-1075/718)<.005,'altar projection/aspect preserved');
console.log('Altar west wall: transparent baked wall removal, matching texture/height, chapel-only scope, altar/platform preservation passed');
