'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const fn=n=>html.match(new RegExp('function '+n+'\\([\\s\\S]*?\\n\\}'))[0];
const c={G:{},rect(g,x,y,w,h,v){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)g[j][i]=v;},bumpTopology(){}};
vm.createContext(c);vm.runInContext(['isCrownEntranceWall','applyCrownEntranceFrame','sealSecretCells','savedSecretFor','restoreSecretEntrances'].map(fn).join('\n'),c);
const sec={i:105,j:15,w:3,h:1,kind:'teeth',face:'n',open:0};
const L=c.G.lvl={n:1,grid:Array.from({length:25},()=>Array(132).fill(0)),secrets:[sec]};
c.applyCrownEntranceFrame(L);
assert(L.grid[15].slice(102,112).every(v=>v===1),'closed bone wall and rubble jambs form one line');
sec.open=1;c.applyCrownEntranceFrame(L);
assert.deepEqual(Array.from(L.grid[15].slice(102,112)),[1,1,1,0,0,0,1,1,1,1],'opening is three cells, both jambs remain solid');
L.grid[15].fill(0);L.grid[20][103]=4;
c.restoreSecretEntrances({secrets:[{...sec}]});
assert.deepEqual(Array.from(L.grid[15].slice(102,112)),[1,1,1,0,0,0,1,1,1,1],'old-save corridor carving cannot erase jambs');
assert.equal(L.grid[20][103],4,'unrelated excavated terrain survives');
sec.open=0;c.restoreSecretEntrances({secrets:[{...sec}]});assert(L.grid[15].slice(102,112).every(v=>v===1));
assert(c.isCrownEntranceWall(L,102,15)&&c.isCrownEntranceWall(L,111,15));
assert(!c.isCrownEntranceWall(L,101,15)&&!c.isCrownEntranceWall({...L,n:2},105,15));
vm.runInContext(['crownEntranceKind','crownEntranceHeight','crownBoneDepth','crownBoneTexture','drawCrownBoneCap','drawCrownEntranceCell','drawSecretFadedFace'].map(fn).join('\n'),c);
for(let x=102;x<112;x++)assert.equal(c.crownEntranceKind(L,x,15),x>=105&&x<108?'bones':'rubble');
assert.equal(c.crownEntranceKind({...L,n:2},105,15),null);
const bones={id:'bones'},rubble={id:'rubble'},rubble2={id:'rubble2'},faces=[],piles=[];
Object.assign(c,{SPR:{crown_bone_wall:bones,rubble,rubble2},ZOOM:1,DIGT:null,hallWallH:()=>80,w2s:(x,y)=>({x:(x-y)*58,y:(x+y)*29}),drawIsoPlaneImg:(g,img,x,y,x1,y1,h)=>{assert.equal(h,90,'bone wall matches rubble height');faces.push(img);},drawBillboard:(g,img,h)=>{assert(h===90||h===90*.58,'jambs retain full height, transition stones overlap bone ends');piles.push({img,h});}});
let caps=0;const g={save(){},restore(){},translate(){},transform(a,b,c,d){assert.equal(a,58);assert(Math.abs(c+58*1.8)<.001);assert.equal(b,29);assert(Math.abs(d-29*1.8)<.001);},fillRect(){caps++;}};
for(let x=102;x<112;x++)assert(c.drawCrownEntranceCell(g,L,x,15,true,false,true,false));
assert.equal(faces.length,8);assert(faces.every(img=>img===bones),'central faces and both thick ends use bone texture');assert.equal(caps,3,'all three bone cells have a full tile-depth cap');
assert.equal(piles.filter(p=>p.h===90).length,21,'seven rubble cells each have three full-height depth banks');assert.equal(piles.filter(p=>p.h===90*.58).length,2,'both bone ends have overlapping broken stone');assert(piles.every(p=>p.img===rubble||p.img===rubble2),'jambs and transitions share rubble assets');
c.secretSeamAt=()=>{throw Error('ordinary secret overlay must not cover bones');};
c.drawSecretFadedFace(g,L,106,15,80,null,null);
assert(fn('drawWorld').includes('if(drawCrownEntranceCell(g,L,x,y,oS,oE,oN,oW))return;'));
assert(html.includes("'crown_bone_wall','wall_teeth_chapel'"),'bone artwork is preloaded');
console.log('Closed/open/reloaded crown entrance, bone faces and seven rubble jamb cells passed');
