'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const fn=n=>html.match(new RegExp('function '+n+'\\([\\s\\S]*?\\n\\}'))[0];
const c={G:{},rect(g,x,y,w,h,v){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)g[j][i]=v;},bumpTopology(){}};
vm.createContext(c);vm.runInContext(['isCrownEntranceWall','applyCrownEntranceFrame','sealSecretCells','savedSecretFor','restoreSecretEntrances'].map(fn).join('\n'),c);
const sec={i:105,j:15,w:3,h:1,kind:'teeth',face:'n',open:0};
const L=c.G.lvl={n:1,grid:Array.from({length:25},()=>Array(132).fill(0)),secrets:[sec]};
c.applyCrownEntranceFrame(L);
assert(L.grid[15].slice(102,112).every(v=>v===1),'closed bone wall and rubble jambs form one line');
sec.open=1;c.applyCrownEntranceFrame(L);
assert.deepEqual(Array.from(L.grid[15].slice(102,112)),[1,1,1,0,0,0,1,1,1,1],'opening is three cells, both jambs remain solid');
L.grid[15].fill(0);L.grid[20][103]=4;
c.restoreSecretEntrances({secrets:[{...sec}]});
assert.deepEqual(Array.from(L.grid[15].slice(102,112)),[1,1,1,0,0,0,1,1,1,1],'old-save corridor carving cannot erase jambs');
assert.equal(L.grid[20][103],4,'unrelated excavated terrain survives');
sec.open=0;c.restoreSecretEntrances({secrets:[{...sec}]});assert(L.grid[15].slice(102,112).every(v=>v===1));
assert(c.isCrownEntranceWall(L,102,15)&&c.isCrownEntranceWall(L,111,15));
assert(!c.isCrownEntranceWall(L,101,15)&&!c.isCrownEntranceWall({...L,n:2},105,15));
const art={width:512},calls=[];
c.secretSeamAt=()=>sec;c.secretFaceOk=()=>true;c.teethChapelWallImg=()=>art;c.secretFaceImg=()=>{throw Error('old secret art used');};c.drawMasonryFace=(g,img)=>calls.push(img);
vm.runInContext(fn('drawSecretFadedFace'),c);c.drawSecretFadedFace({},L,106,15,30,null,null);assert.equal(calls[0],art,'bone gate keeps chapel art in the late secret pass');
const render=fn('drawWorld');
assert(render.includes('entrance||(sf===\'n\'?secN:'),'bone gate overrides old secret art');
assert(render.includes('entrance||altarWest||(sf===\'e\'?secE:faceR)')&&render.includes('entrance||faceL'),'jamb side and rear faces use matching bone art');
console.log('Closed/open/reloaded crown entrance, solid jambs and shared bone-masonry renderer passed');
