'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const fallback=html.match(/function drawStairWell\([\s\S]*?\n\}/)[0];
const c={propSpriteH:()=>138};vm.createContext(c);vm.runInContext(fallback,c);
let steps=0;c.drawStairWell({save(){},restore(){},fillRect(){steps++;}},1,{});
assert.equal(steps,6,'missing-art fallback draws six stone steps');
assert(!/ellipse|arc\(/.test(fallback),'no circular pit or torch marker');
assert(!html.includes("if(p.k==='stairs') drawStairWell(g,z,p);"),'painted stairs render without procedural overlay');
const metric=html.match(/function tilesetPropMetric\(k, L\)\{[\s\S]*?\n\}/)[0];
assert(!/k==='stairs'/.test(metric),'painted stairs retain full proportions');
assert(html.includes("if(k==='stairs') return 138*z*(p.s||1)"));
assert(fs.existsSync(path.join(__dirname,'../../assets/props/prop_stairs.png')));
console.log('Stairs-only artwork, full proportions and six-step fallback passed');
